"""Async Python SDK for the Sogni Supernet."""

from .account import AccountApi, CurrentAccount
from .announcements import AnnouncementsApi
from .attribution import (
    build_sogni_attribution_headers,
    buildSogniAttributionHeaders,
    normalize_connection_attribution,
    normalizeConnectionAttribution,
    resolve_workload_attribution,
    resolveWorkloadAttribution,
    workload_attribution_to_wire_fields,
    workloadAttributionToWireFields,
)
from .auth import ApiKeyAuthManager, CookieAuthManager, TokenAuthManager
from .chat import (
    ChatApi,
    ChatStream,
    ChatToolsApi,
    SogniTools,
    is_sogni_tool_call,
    isSogniToolCall,
    parse_tool_call_arguments,
    parseToolCallArguments,
)
from .client import AsyncSogniClient, SogniClient
from .errors import (
    RETRYABLE_CHAT_ERROR_TYPES,
    SUBSCRIPTION_ERROR_CODES,
    ApiError,
    ChatJobError,
    ProjectError,
    SogniError,
    is_retryable_chat_error,
    is_subscription_limit_error,
    isRetryableChatError,
    isSubscriptionLimitError,
)
from .events import DataEntity, EventEmitter
from .personal_loras import PersonalLoras
from .projects import (
    VIDEO_WORKFLOW_ASSETS,
    Job,
    Project,
    ProjectsApi,
    create_job_request_message,
)
from .recovery import (
    PROJECT_LOST_ERROR,
    PROJECT_LOST_ORIGINAL_CODE,
    is_project_lost_error,
    isProjectLostError,
    project_params_from_recovered_project,
    projectParamsFromRecoveredProject,
)
from .replay import ReplayApi
from .stats import StatsApi
from .utils import (
    BIREFNET_BACKGROUND_REMOVAL_MODEL_ID,
    FLASHVSR_VIDEO_UPSCALE_MODEL_ID,
    MINIMAX_H3_FASTH3_A2V_MODEL_ID,
    MINIMAX_H3_FASTH3_FLFA2V_MODEL_ID,
    MINIMAX_H3_FASTH3_IA2V_MODEL_ID,
    PIXAL3D_IMAGE_TO_3D_MODEL_ID,
    PIXAL3D_MULTIVIEW_IMAGE_TO_3D_MODEL_ID,
    PIXAL3D_ORBIT_VIEW_SLOTS,
    SAM3_IMAGE_SEGMENT_MODEL_ID,
    calculate_video_frames,
    get_minimax_h3_frames_for_audio_duration,
    get_pixal3d_orbit_view_slots,
    getMinimaxH3FramesForAudioDuration,
    getPixal3dOrbitViewSlots,
    is_audio_model,
    is_minimax_h3_audio_guide_model,
    is_model_artifact_model,
    is_pixal3d_model,
    is_pixal3d_multiview_model,
    is_segmentation_model,
    is_video_model,
    is_video_upscale_model,
    isAudioModel,
    isMinimaxH3AudioGuideModel,
    isModelArtifactModel,
    isPixal3dModel,
    isPixal3dMultiViewModel,
    isSegmentationModel,
    isVideoModel,
    isVideoUpscaleModel,
    parse_creative_workflow_sse_chunk,
    parseCreativeWorkflowSseChunk,
    requires_starting_image,
    requiresStartingImage,
)
from .workflows import (
    CREATIVE_WORKFLOW_WAITING_REASONS,
    CreativeWorkflowsApi,
    CreativeWorkflowTemplatesApi,
)

__version__ = "5.54.1"

__all__ = [
    "BIREFNET_BACKGROUND_REMOVAL_MODEL_ID",
    "FLASHVSR_VIDEO_UPSCALE_MODEL_ID",
    "CREATIVE_WORKFLOW_WAITING_REASONS",
    "MINIMAX_H3_FASTH3_A2V_MODEL_ID",
    "MINIMAX_H3_FASTH3_FLFA2V_MODEL_ID",
    "MINIMAX_H3_FASTH3_IA2V_MODEL_ID",
    "PIXAL3D_IMAGE_TO_3D_MODEL_ID",
    "PIXAL3D_MULTIVIEW_IMAGE_TO_3D_MODEL_ID",
    "PIXAL3D_ORBIT_VIEW_SLOTS",
    "PROJECT_LOST_ERROR",
    "PROJECT_LOST_ORIGINAL_CODE",
    "RETRYABLE_CHAT_ERROR_TYPES",
    "SAM3_IMAGE_SEGMENT_MODEL_ID",
    "SUBSCRIPTION_ERROR_CODES",
    "VIDEO_WORKFLOW_ASSETS",
    "AccountApi",
    "AnnouncementsApi",
    "ApiError",
    "ApiKeyAuthManager",
    "AsyncSogniClient",
    "ChatApi",
    "ChatJobError",
    "ChatStream",
    "ChatToolsApi",
    "CookieAuthManager",
    "CreativeWorkflowTemplatesApi",
    "CreativeWorkflowsApi",
    "CurrentAccount",
    "DataEntity",
    "EventEmitter",
    "Job",
    "PersonalLoras",
    "Project",
    "ProjectError",
    "ProjectsApi",
    "ReplayApi",
    "SogniClient",
    "SogniError",
    "SogniTools",
    "StatsApi",
    "TokenAuthManager",
    "calculate_video_frames",
    "build_sogni_attribution_headers",
    "buildSogniAttributionHeaders",
    "create_job_request_message",
    "get_minimax_h3_frames_for_audio_duration",
    "getMinimaxH3FramesForAudioDuration",
    "get_pixal3d_orbit_view_slots",
    "getPixal3dOrbitViewSlots",
    "is_audio_model",
    "is_minimax_h3_audio_guide_model",
    "is_model_artifact_model",
    "is_pixal3d_model",
    "is_pixal3d_multiview_model",
    "is_project_lost_error",
    "is_retryable_chat_error",
    "is_segmentation_model",
    "is_sogni_tool_call",
    "is_subscription_limit_error",
    "is_video_model",
    "is_video_upscale_model",
    "isAudioModel",
    "isMinimaxH3AudioGuideModel",
    "isModelArtifactModel",
    "isPixal3dModel",
    "isPixal3dMultiViewModel",
    "isProjectLostError",
    "isRetryableChatError",
    "isSegmentationModel",
    "isSogniToolCall",
    "isSubscriptionLimitError",
    "isVideoModel",
    "isVideoUpscaleModel",
    "normalize_connection_attribution",
    "normalizeConnectionAttribution",
    "parse_creative_workflow_sse_chunk",
    "parse_tool_call_arguments",
    "parseCreativeWorkflowSseChunk",
    "parseToolCallArguments",
    "project_params_from_recovered_project",
    "projectParamsFromRecoveredProject",
    "requires_starting_image",
    "requiresStartingImage",
    "resolve_workload_attribution",
    "resolveWorkloadAttribution",
    "workload_attribution_to_wire_fields",
    "workloadAttributionToWireFields",
]
